# this file is taken from:
# https://github.com/joeynmt/joeynmt/blob/master/configs/transformer_wmt17_ende.yaml

name: "baseline_transformer_spm_factor_rel_tune_de"

data:
    src: "sign"
    trg: "spm.en"
    factors: ["sign+", "feat_col", "feat_row", "feat_x", "feat_y", "feat_x_rel", "feat_y_rel"]
    train: "data_de/train"
    dev:   "data_de/dev"
    test:  "data_de/test"
    level: "word"
    lowercase: False
    max_sent_length: 500
    # changes for factors:
    factor_voc_limit: 10000
    factor_voc_min_freq: 1
    use_factor: True

testing:
    beam_size: 5
    alpha: 1.0
    postprocess: False

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 7
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0001
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.2
    batch_size: 32
    eval_batch_size: 32
    batch_multiplier: 1
    early_stopping_metric: "eval_metric"
    epochs: 300
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 200
    print_valid_sents: [0, 1, 2, 3, 6]
    keep_last_ckpts: 1
    model_dir: "models/baseline_transformer_spm_factor_rel_tune_de"
    load_model: "models/baseline_transformer_spm_factor_rel_tune_de/latest.ckpt"

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 400
            scale: True
            dropout: 0.5
        # changes for factors:
        factor_embeddings:
            embedding_dim: 16
            scale: True
            dropout: 0.5
        factor_combine: "concatenate"
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.5
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.5
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.5

